#!/usr/bin/env groovy


// Stages template
def buildStage
def gitStage
def dockerStage
def helmStage
def testsStage
def deployStage


node('agent') {
    try {
        // Set Job's ENVs
        env.VAR_PATH = 'jenkins/helloworld1/project.var'

        // Run Prepare stage
        stage('Prepare') {

            checkout(scm)

            println('Load Project vars...')
            load(env.VAR_PATH)

            println('Load Stages..')
          //  buildStage = load(env.Build)
            gitStage = load(env.Git)
            dockerStage = load(env.Docker)
            helmStage = load(env.Helm)
            testsStage = load(env.Tests)
            deployStage = load(env.Deploy)

        }

        // Run Git Stage
        gitStage.GitClone(project: env.PROJECT)


        // Run Build Stage
        buildStage.BuildProject(project: env.PROJECT)


        // Run Docker Stage
        dockerStage.BuildImage(project: env.PROJECT,
                               version: env.VERSION)


        // Run Helm Stage
        helmStage.HelmPackage(project: env.PROJECT,
                              version: env.VERSION)


        // Run Unittests Stage
        tetstsStage.UnitTest(project: env.PROJECT)
        

        // Run Deploy Stage
        deployStage.Deploy(project: env.PROJECT)

    } catch (Exception errJob) {
        println(errJob)
        currentBuild.result = 'FAILURE'
    } finally {
       println("Finally")
    }
}